### ISSUE TITLE
Issue calling broadcast methods comment

### ISSUE THREAD

**Issue by roboza** [dragosroua/steem-api-tools#3]
Attempting to call `->comment()` and getting error api method does not exist.

I tried amending the code to add `broadcast.comment` which got me past the first part but now keep getting invalid request. Anyone else having this issue?

**Comment by dragosroua** [comment]
Thanks, will look into it.

**Comment by allninja** [comment]
any update on this?

**Comment by dragosroua** [comment]
The API calls need to be refactored for the new backend. Will post an update as soon as I get to it.
